name: paudha_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.1
  http: ^1.2.0
  photo_view: ^0.14.0
  image_picker: ^0.8.5+3 
  camera: ^0.10.0+4
  path: ^1.8.0 
  easy_localization: ^3.0.7
  permission_handler: ^10.0.0
  path_provider: ^2.0.10 # To store images locally
  flutter_localizations:
    sdk: flutter
  


  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.6
  validators: ^3.0.0
  flutter_dotenv: ^5.2.1
  flutter_easyloading: ^3.0.5
  http_parser: ^4.1.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0



# The following section is specific to Flutter packages.
flutter:
  
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - .env
    - assets/translations/